### ISSUE TITLE
Thanks for your contribution

### ISSUE THREAD

**Issue by RAJU2529** [pal1000/MEUpdateEasy#1]
Just now i  came across your article. i liked your fwscript bat file. I hope this script will be useful to all windows users.
I require you to give some examples with photos from your own experience

**Comment by pal1000** [comment]
@platomav is the author of the article from win-raid forums, not me.
Also I don't have hardware new enough to receive ME firmware updates from Intel anymore. As far as I know Intel discontinued ME firmware versions prior to 10.x so everything older than Broadwell doesn't get ME firmware updates anymore so I can't record the process or provide screenshots, sorry.
